---
- name: Check for nodejs
  command: which nodejs
  ignore_errors: True
  register: nodejs_exists
- name: Install nodejs
  apt: name=nodejs
  when: not nodejs_exists.stdout_lines
- name: Install libpq-dev
  apt: name=libpq-dev
- name: Install "validation-tracker" node.js package globally
  npm: name=validation-tracker global=yes state=latest
- name: Copy validation-tracker.conf
  template: src=upstart.conf.j2 dest=/etc/init/validation-tracker.conf
- name: Start validation-tracker
  service: name=validation-tracker state=restarted
